# Site settings
keywords: "murilo godoy, advocacia internacional, direito internacional"
author:
url: "https://mgadvocaciainternacional.com"

# Build settings
markdown: kramdown
theme: null
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
