# Site settings
title: Murilo Godoy - Advocacia Internacional
description: >-
  Trabalhando com diversas áreas da pratica jurídica, destacando consultorias jurídicas internacionais, estudos fiscais e aduaneiros da União Europeia, família internacional, tributário internacional, direito de starup e open innovation e representações à pessoa coletiva (PJ's) na união europeia.
keywords:
author:
url: "https://mgadvocaciainternacional.com"

# Build settings
markdown: kramdown
theme: null
sass:
  style: compressed
plugins:
  - jekyll-sitemap
